import { faGithub, faLinkedin } from '@fortawesome/free-brands-svg-icons';

import badMetronomePng from './assets/bad-metronome.png';
import badMetronomeWebp from './assets/bad-metronome.webp';
import breatheCalmlyPng from './assets/breathe-calmly.png';
import breatheCalmlyWebp from './assets/breathe-calmly.webp';
import rollPwdPng from './assets/roll-pwd.png';
import rollPwdWebp from './assets/roll-pwd.webp';
import simpleChordsPng from './assets/simple-chords.png';
import simpleChordsWebp from './assets/simple-chords.webp';
import simpleQrCreatePng from './assets/simple-qr-create.png';
import simpleQrCreateWebp from './assets/simple-qr-create.webp';
import simpleScalesPng from './assets/simple-scales.png';
import simpleScalesWebp from './assets/simple-scales.webp';
import underwindPng from './assets/underwind.png';
import underwindWebp from './assets/underwind.webp';

import type { Education, Experience, Link, Sample, TextCategory } from './types';

export const SkillsData: TextCategory = {
	'AI & Machine Learning': [
		'ChatGPT',
		'Claude',
		'Context Engineering',
		'Copilot',
		'Cursor',
		'DeepSeek',
		'Google Gemini',
		'Grok',
		'Kimi',
		'Midjourney',
		'Mistral',
		'OpenAI API',
		'Prompt Engineering',
		'Qwen',
		'Stable Diffusion',
		'T3.chat',
	],
	'Back-End Development': [
		'.NET',
		'APIs',
		'C',
		'C#',
		'C++',
		'Express.js',
		'NextJS',
		'Node Package Manager (NPM)',
		'Node Version Manager (NVM)',
		'Node.js',
		'Performant NPM (PNPM)',
		'PHP',
		'Python',
		'SvelteKit',
		'VBA',
	],
	Business: [
		'Adobe Acrobat',
		'Budgeting',
		'Compliance',
		'Contract Negotiation',
		'Contractor Management',
		'Contracts',
		'Customer Service',
		'Digital Marketing',
		'Documentation',
		'Drafting',
		'E-Commerce',
		'Generative Engine Optimization (GEO)',
		'Google Analytics',
		'Google G Suite',
		'KPIs',
		'Legal Analysis',
		'Legal Drafting',
		'Market Research',
		'Marketing',
		'Microsoft 365',
		'Microsoft Office',
		'Pricing Strategies',
		'Process Development',
		'Product Roadmapping',
		'Profitability',
		'Proofreading',
		'Revenue Generation',
		'SaaS (Software as a Service)',
		'Sales',
		'Search Engine Optimization (SEO)',
		'Strategic Planning',
	],
	'CI/CD': ['GitHub Actions', 'Vercel'],
	'Data Formats': ['JSON', 'Markdown', 'MDX', 'XML'],
	Databases: [
		'Database Architecture',
		'FileMaker',
		'MariaDB',
		'Microsoft Access',
		'MySQL',
		'Normalization',
		'SQL',
	],
	Design: [
		'Adobe Illustrator',
		'Adobe InDesign',
		'Adobe Photoshop',
		'Adobe XD',
		'Affinity Designer',
		'Affinity Photo',
		'Canva',
		'Data Presentation',
		'Figma',
		'InVision',
	],
	DevOps: [
		'Amazon Web Services (AWS)',
		'Apache',
		'Azure',
		'Bash',
		'Cloudflare',
		'Dev Tools',
		'Docker',
		'Google Cloud Platform (GCP)',
		'LAMP',
		'Linux Server Administration',
		'Local Development',
		'Nginx',
		'PowerShell',
		'Raspberry Pi',
		'Terraform',
	],
	'Front-End Development': [
		'AJAX',
		'Bootstrap',
		'Cross-Browser Compatibility',
		'Cross-Device Compatibility',
		'CSS',
		'CSS Flexbox',
		'CSS Grid',
		'CSS Modules',
		'ECMAScript (ES6+)',
		'HTML',
		'HTML5',
		'JavaScript',
		'jQuery',
		'Nativewind',
		'React',
		'React Native',
		'Responsive Web Design',
		'SCSS/SASS',
		'Svelte',
		'Tailwind CSS',
		'TypeScript',
	],
	Management: [
		'Agile',
		'Conflict Management',
		'Conflict Resolution',
		'Estimating',
		'Kanban',
		'Leadership',
		'Leadership & Management',
		'Management',
		'Problem Solving',
		'Risk Management',
		'Scrum',
		'Stakeholder Management',
		'Standard Operating Guidelines (SOG)',
		'Standard Operating Procedures (SOP)',
		'Team Leadership',
	],
	Mentorship: [
		'Code Reviews',
		'Knowledge Sharing',
		'Mentoring',
		'Office Hours',
		'Pair Programming',
		'Tutoring',
	],
	'Operating Systems': ['Android', 'ChromeOS', 'iOS', 'Linux', 'macOS', 'Windows'],
	Paradigms: [
		'Functional Programming',
		'Model View Controller (MVC)',
		'Object-Oriented Programming (OOP)',
	],
	'State Management': [
		'Context API',
		'Jotai',
		'TanStack Form',
		'TanStack Query',
		'TanStack Router',
		'Zustand',
	],
	Teaching: [
		'Curriculum Development',
		'Lesson Planning',
		'Presentation Skills',
		'Socratic Method',
		'Workshop Facilitation',
	],
	Testing: [
		'Behavior-Driven Development (BDD)',
		'Browser Compatibility Testing',
		'Cross-Device Compatibility Testing',
		'Cypress',
		'Jest',
		'JSDOM',
		'PHPUnit',
		'Playwright',
		'React Testing Library',
		'Selenium',
		'Test-Driven Development (TDD)',
		'Unit Testing',
		'Vitest',
	],
	'UI/UX': [
		'Accessibility',
		'Interaction Design',
		'Prototyping',
		'Sketch',
		'UI',
		'User Research',
		'User Satisfaction',
		'User Stories',
		'UX',
		'Wireframing',
	],
	'Version Control': ['Bitbucket', 'CVS', 'Git', 'GitHub', 'GitLab'],
	WordPress: [
		'Advanced Custom Fields (ACF)',
		'Gutenberg Blocks',
		'Local By Flywheel',
		'Multisites',
		'Plugin Development',
		'Theme Development',
		'WooCommerce',
		'WP REST API',
		'WP-CLI',
	],
};

export const KnowledgeData: TextCategory = {
	Technology: ['Google Analytics (Certified)', 'React & NextJS', 'WordPress'],
	Law: [
		'Michigan Licensed Attorney',
		'Constitutional Law',
		'Contracts',
		'Evidence',
		'Real Estate & Property',
		'Remedies',
	],
};

export const ExperienceData: Experience[] = [
	{
		title: 'Lead Web Solutions Specialist',
		company: 'Patriot Technology, Esquire',
		dates: 'November 2022 - Present',
		location: 'Grand Rapids, MI',
		items: [
			'Developing custom web apps with React, Typescript, Tailwind CSS, NextJS and other industry-standard tools and practices.',
			'Leveraging Cloudflare, Amazon Web Services and other cloud-based SaaS products and services to ensure 99.9% guaranteed uptime.',
			'Building dynamic and user-friendly WordPress websites—including custom themes, plugins and integrations, reducing third-party dependencies by 40%.',
			'Designing, developing, testing, launching and servicing hundreds of custom WordPress Themes & Plugins to satisfy client specifications.',
			'Strategizing with clients to explore and negotiate cost-effective solutions for tech and business issues.',
			'Diagnosing and debugging both basic and complex web technology problems.',
			'Using ChatGPT, Copilot and other AI to deliver 48% higher quality code 55% faster.',
			'Led the architecture of six Template Themes, individualized with a simple but robust interface that automatically compiles styling (launched on over 100 websites across the country).',
			'Converted legacy app built with ASP and React to a custom solution built with Svelte, SvelteKit and C# to reduce processing latency by 91%.',
		],
	},
	{
		title: 'Attorney & Developer',
		company: 'Kyle Michael Sullivan, PLLC',
		dates: 'September 2014 - Present',
		location: 'Grand Rapids, MI',
		items: [
			'Practicing in several areas of law—including Real Estate Transactions, Estate Planning, Contract Law, Corporate Operations, Personal Injury, Criminal Law and Family Law.',
			'Regularly using "Plain English" to write clear, easy-to-understand legal documents, diagrams and educational materials.',
			'Constructing an open-source framework and freemium GUI with NextJS, React and Linux to automate individualized document creation, reducing document production time by 52%.',
			'Leveraging web technologies to create a seamless, secure workflow, resulting in a 40% increase in client satisfaction.',
			'Automate captions for filings, correspondence and boilerplate to create documents with 12% greater accuracy and 70% less time.',
			'Built my own practice management software to organize my database, develop secure file storage systems and explore ways to mitigate common pain-points, increasing overall efficiency by 34%.',
		],
	},
	{
		title: 'Director of Website Technology',
		company: 'Royal Media',
		dates: 'September 2022 - July 2023',
		location: 'New York, NY',
		items: [
			'Collaborated with management, team members, customers and vendors to implement tailored and responsive web experiences with HTML, CSS, Javascript, PHP and MySQL.',
			'Built, standardized, optimized, supported and updated WordPress websites, themes and plugins, resulting in a 25% increase in load speeds.',
			'Managed 15 intertwining e-commerce stores that sell digital subscriptions, event tickets and data analysis tools covering air freight, financial services and other technical industries.',
			'Led Test & Analytics Committee that improves content, UI/UX, workflow and SEO of websites, leading to a 31% increase in conversions and 30% increase in revenue.',
			'Headed developer operations—including providing uninterrupted server access, maintaining multiple environments, managing backups, DNS and Git version control.',
			'Implemented proprietary integrations between WordPress, WooCommerce, HubSpot and QuickBooks, streamlining operations and reducing manual entry errors by 69%.',
			'Tracked and documented team success with Basecamp—resolving 95% of support tickets within 24 hours.',
			'Ensured compliance with different legal, regulatory, contractual and policy requirements—including GDPR and CCPA.',
			'Leveraged Google products—including Analytics, Authenticator, Fonts, Sheets, Tag Manager—to enhance website performance, increasing user engagement by 20%.',
			'Evangelized team-building and continuing education—averaging six classes and two books per month—fostering and expanding a diverse and inclusive culture of continuous improvement.',
		],
		href: 'https://royalmedia.com/',
	},
	{
		title: 'Senior Full Stack Developer',
		company: 'DDM Marketing & Communications',
		dates: 'October 2021 - September 2022',
		location: 'Grand Rapids, MI',
		items: [
			'Built and tested custom WordPress Themes for clients in highly regulated industries—e.g., healthcare, financial services, sophisticated manufacturing—to ensure responsive cross-browser success.',
			'Programmed custom WordPress Plugins to handle data management, SMTP processing, and style standardization—increasing client satisfaction by 30%.',
			'Overhauled and documented WordPress Maintenance process to include safeguards to maximize consistent quality with minimal effort.',
			'Optimized UI/UX for all user types with formal and informal tests, increasing user engagement by 28%.',
			'Developed with Agile, using sprints, stand-ups, Git and Jira (building custom dashboards and filters).',
			'Cofounder and Leader of the "New Crew": a mentorship group to welcome and acquaint new employees, reducing onboarding time by 41%.',
		],
		href: 'https://teamddm.com/',
	},
	{
		title: 'Senior WordPress Developer',
		company: 'Diocesan Publictions',
		dates: 'September 2018 - September 2022',
		location: 'Byron Center, MI',
		items: [
			'Designed, developed, tested, launched and serviced hundreds of custom-built WordPress Themes & Plugins to satisfy client specifications.',
			'Led the architecture of five Template Themes, individualized with a simple but robust interface that automatically compiles styling (launched on over 100 websites across the country since Covid-19).',
			'Pioneered dynamic interfaces with JavaScript and PHP, increasing department’s offerings and expediting deliverables by 36%.',
			'Introduced team to Git, SCSS, React, JSX, minification, and other best practices, increasing development efficiency by 40%.',
			'Collaborated with Project Manager and Content Specialists to ensure timely and efficient delivery, achieving 95% on-time completion.',
			'Inspired and collaborated with the frontend team, designers and backend developers, enhancing team productivity by 25%.',
		],
		href: 'https://diocesan.com/',
	},
	{
		title: 'Senior Lead Developer',
		company: 'Spotlead',
		dates: 'May 2018 - September 2018',
		location: 'Grand Rapids, MI',
		items: [
			'Successfully oversaw growing global team’s operations related to design, development, testing and troubleshooting.',
			'Deployed rapid prototyping with Adobe XD and Snagit.',
			'Sold tailored WordPress websites and upgrades with Proposify and Ziflow, increasing sales by 20%.',
			'Expanded organic traffic with individualized SEO consulting, boosting website traffic by 35%.',
			'Communicated with clients via Zoom to ensure satisfaction before it was cool.',
		],
		href: 'https://spotlead.com/',
	},
	{
		title: 'Chief Technology Officer',
		company: 'Green Property Management',
		dates: 'June 2016 - April 2018',
		location: 'Grand Rapids, MI',
		items: [
			'Developed proprietary technologies for many common aspects of property management—including screening, marketing, valuation, internal auditing, and turns.',
			'Standardized and documented procedures to improve efficiency, increase revenue, reduce waste and enhance internal and external satisfaction, resulting in a significant revenue increase and 64% higher tenant satisfaction ratings.',
			'Reworked the company website, improving usability, providing real-time unit availability and increasing load times by 86%.',
			'Redesigned the VoIP phone system, maximizing efficiency and increasing response times by 72%.',
			'Reorganized the database clusters, standardizing data and enhancing intelligently populating forms.',
			'Developed a move-out inspection procedure, allocating liability for property damage and generating substantial revenue.',
			'Facilitated the acquisition and disposition of real estate, ensuring statutory and regulatory compliance.',
			'Negotiated, drafted and reviewed many legal documents—including residential and commercial leases, property management agreements, deeds and compliance documents.',
		],
		href: 'https://www.livegreenlocal.com/',
	},
];

export const EducationData: Education[] = [
	{
		degree: 'Juris Doctor',
		school: 'Western Michigan University Thomas M. Cooley Law School',
		location: 'Grand Rapids, MI',
	},
	{
		degree: 'Bachelor’s Degree',
		school: 'University of Michigan',
		location: 'Ann Arbor, MI',
	},
];

export const LinksData: Link[] = [
	{
		label: 'LinkedIn',
		href: 'https://www.linkedin.com/in/kyle-michael-sullivan/',
		icon: faLinkedin,
	},
	{
		label: 'GitHub',
		href: 'https://github.com/kylemichaelsullivan',
		icon: faGithub,
	},
];

export const SampleData: Sample[] = [
	{
		title: 'Breathe Calmly',
		source: 'https://github.com/kylemichaelsullivan/breathe-calmly',
		interactive: 'https://breathecalmly.com/',
		imagePng: breatheCalmlyPng,
		imageWebp: breatheCalmlyWebp,
	},
	{
		title: 'Roll Password Generator',
		source: 'https://github.com/kylemichaelsullivan/roll-pwd',
		interactive: 'https://rollpwd.vercel.app/',
		imagePng: rollPwdPng,
		imageWebp: rollPwdWebp,
	},
	{
		title: 'Simple Scales',
		source: 'https://github.com/kylemichaelsullivan/simple-scales',
		interactive: 'https://simplescales.vercel.app/',
		imagePng: simpleScalesPng,
		imageWebp: simpleScalesWebp,
	},
	{
		title: 'Simple Chords',
		source: 'https://github.com/kylemichaelsullivan/simple-chords',
		interactive: 'https://simplechords.vercel.app/',
		imagePng: simpleChordsPng,
		imageWebp: simpleChordsWebp,
	},
	{
		title: 'Bad Metronome',
		source: 'https://github.com/kylemichaelsullivan/bad-metronome',
		interactive: 'https://badmetronome.com/',
		imagePng: badMetronomePng,
		imageWebp: badMetronomeWebp,
	},
	{
		title: 'Simple QR Create',
		source: 'https://github.com/kylemichaelsullivan/simple-qr-create',
		interactive: 'https://simple-qr-create.vercel.app/',
		imagePng: simpleQrCreatePng,
		imageWebp: simpleQrCreateWebp,
	},
	{
		title: 'Underwind',
		source: 'https://github.com/kylemichaelsullivan/underwind',
		imagePng: underwindPng,
		imageWebp: underwindWebp,
	},
];
